### ISSUE TITLE
streetSmartToggleTool über dn_urltoolactivator

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-streetsmart#10]
Über das Developer-Network-Bundle „dn_urltoolactivator“ können Werkzeuge mit der App gestartet werden. So auch das Tool “streetSmartToggleTool“. Wird jedoch das Tool über den toolactivator gestartet, erfolgt keine Initialisierung des Layers "streetSmartLayerId". Wird das Tool innerhalb der App aufgerufen, funktioniert alles wie gewünscht.

**Comment by gedicb** [comment]
Mit der map.apps Version 4.15.0 kann das “streetSmartToggleTool“ gar nicht mehr über das Bundle „dn_urltoolactivator“ gestartet werden.

**Comment by sholtkamp** [comment]
Wir haben eine neue Version des Bundles "dn_urltoolactivator" veröffentlicht. Diese finden Sie [hier](https://github.com/conterra/mapapps-url-toolactivator/releases/tag/2.1.0).
Mit dieser neuen Version sollte das Problem behoben sein.

**Comment by gedicb** [comment]
Leider hat die neue Version das beschriebene Problem nicht behoben. Das “streetSmartToggleTool“ kann nicht über das Bundle „dn_urltoolactivator“ gestartet werden.

**Comment by sholtkamp** [comment]
Haben Sie versucht, den Parameter "activationDelay" des Bundles [dn_urltoolactivator](https://github.com/conterra/mapapps-url-toolactivator/tree/master/src/main/js/bundles/dn_urltoolactivator#dn_urltoolactivator) wie in der hier verlinkten Dokumentation zu setzen? Bei unseren Testversuchen hat sich ein Wert von etwa 2000 bewährt.
