### ISSUE TITLE
dn_streetsmart und dn_sketchingenhanced

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-streetsmart#11]
Das Bundle dn_streetsmart erzeugt zur Darstellung des aktuell gewählten Panoramabildes den Layer StreetSmartMarkerGraphicLayer. Dieser Layer wird ebenfalls in dem Bundle dn_sketchingenhanced als aktiver Fanglayer angezeigt. Dieses Verhalten ist meiner Auffassung nach nicht sinnvoll, daher sollte dieser Layer seitens des Bundles dn_streetsmart für das Bundle dn_sketchingenhanced nicht angeboten werden.
![dn_streetsmart](https://github.com/conterra/mapapps-streetsmart/assets/60434030/1454f02c-2a28-490d-aad1-aacdb98b53ad)

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-streetsmart/releases/tag/1.3.1
